#!/bin/bash
# vim:ts=4
# program: Using to note the knowledge about Greasemonkey
# made by: Engells
# date: Jan 24, 2021
# content: Just for memo


建議管理器
====================
Tampermonkey	https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
Violent monkey	https://addons.mozilla.org/firefox/addon/violentmonkey/



建議腳本及來源網站
====================
懒人专用，全网VIP视频免费破解去广告、全网音乐直接下载、百度网盘直接下载、知乎视频下载等多合一版。长期更新，放心使用。
Search By Image | 以图搜图
AC-baidu-重定向优化百度搜狗谷歌必应搜索_favicon_双列

Greasy Fork*	https://greasyfork.org/zh-TW
UserScripts		https://userscripts-mirror.org/scripts.html
OpenUserJS	 	https://openuserjs.org/
Sleazy Fork		https://sleazyfork.org/zh-TW



URL
====================
自用油猴脚本推荐  https://www.zhyong.cn/posts/d265/
有哪些超神的油猴脚本  https://www.zhihu.com/question/22210090
Google Chrome 浏览器插件和油猴脚本推荐  https://wsgzao.github.io/post/chrome-extensions/


