# vim:ts=4
#=================== Global Settings ==================== 
[global]
	workgroup = KINET 
	netbios name = ubuntu
	server string = Samba Server %v

	# locale encoding
	display charset = utf8
	unix charset = utf8
	dos charset = cp950

	# log mechanism
	log file = /var/log/samba/log.%m
	max log size = 50

	# 與密碼有關的設定項目，包括密碼檔案格式
	security = user		# 使用者認證層級設為 user
	encrypt passwords = Yes
	passdb backend = tdbsam		# 密碼檔案採 TDB 資料庫格式，預設檔案在 /var/lib/samba/private/
	#obey pam restrictions = yes

	# 其他設定
	#map to guest = bad user
	dns proxy = no
	load printers	= no
	hosts allow = 127.192.168.10.

#================== Share Definitions =================== 
[shared]
	comment = Data space between host and virtual machime
	path = /home/engells/virtual/shared 
	browsable =yes
	read only = no
	writable = yes
	#create mode = 0644		# 建立檔案的權限為 664
	#directory mode = 0775	# 建立目錄的權限為 775
	#writelist = 			# user, @group
	guest ok = yes
